FEATURE: make dependency to oauth2_proxy conditional
punktDe/ansible-proserver-mailhog pull request #1
Opened 2021-04-09 15:43 UTC by Corvan

Reason: the dependency brakes execution in projects where no oauth2 server is available

2021-04-10 13:08 UTC, fnkr requested changes

2021-04-10 13:08 UTC, fnkr commented on meta/main.yaml
> +    when: mailhog.oauth2.proxy
Did you mean `mailhog.oauth2_proxy`?

2021-04-11 10:19 UTC, Corvan commented
Addendum: the directory roles/oauth2_proxy has to exist, even if you don't use it, but it can be empty then, when you don't use the oauth2_proxy role. Maybe this should be documented.

2021-04-13 09:09 UTC, fnkr approved these changes

2021-04-13 09:10 UTC, merged